export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  //app-component
  'home': 'Home page',
  'loading': 'Loading in progress. Pleas wait.',
  'OX': 'Tic tac toe',
  'facebook': 'Log in with Facebook',
  'Moje konto': 'My account',

  //edit-data
  'Podaj imie!': 'Enter your name!',
  'Podaj poprawne imie!': 'Enter correct name!',
  'Imie moze zawierac maksymalnie 100 znakow!': 'Name can include only 100 chars!',
  'Imie': 'Name',
  'Nazwisko': 'Last name',
  'Podaj nazwisko!': 'Enter your last name!',
  'Podaj poprawne nazwisko!': 'Enter correct last name!',
  'Nazwisko moze zawierac maksymalnie 100 znakow!': 'Last name can include only 100 chars!',
  'Obywatelstwo': 'Nationality',
  'Podaj swoje obywatelstwo!': 'Select your nationality!',
  'Edytuj dane': 'Edit your personal data',
  'Wyloguj': 'Logout',
  'Usluga chwilowo niedostepna, sprobuj ponownie pozniej.': 'Service temporary unavailable, please try again later.',
  'Edycja zakonczona powodzeniem': 'Editing personal data finished successful.',

  //fbLogin
  'Wyswietl informacje': 'Show information',

  //home_component
  'Strona startowa':'Home page',
  'p1':'Page was created as a project for subject \"Programowanie w internecie\" ',
  'p2':'Web application uses angular and web server uses node.js with express framework and ORM Sequelize',
  'p3':'Link to the web application: ',
  'p4':'Link to the server: ',
  'kliknij tutaj': 'click here',

  //login
  'Logowanie': 'Login',
  'Podaj email!': 'Podaj email!',
  'Podaj poprawny adres email!': 'Eneter correct email address!',
  'Podaj haslo!': 'Enter password!',
  'Email': 'Email',
  'Haslo': 'Password',
  'Zaloguj': 'Sign in',
  'Zarejestruj sie': 'Register',
  'Zapomniales hasla?': 'Forgot password?',
  'Bledny email lub haslo':'Incorrect email or password',

  //OX
  'Gracz: X': 'Player: X',
  'Kolko i krzyzyk': 'Tic tac toe',
  'Nowa gra':'New game',

  //register
  'Pomyslnie zarejestrowano uzytkownika': 'User registered successfully!',
  'Podany adres email jest juz zajety': 'The email you have entered is already taken',
  'Podane hasla sa rozne.': 'Entered passwords are different.',
  'Podaj adres email!': 'Enter email address!',
  'Email moze zawierac maksymalnie 100 znakow!':'Email can include only 100 characters!',
  'Haslo musi zawierac minimum 6 znakow!': 'Password has to include at least 6 characters!',
  'Haslo moze zawierac maksymalnie 100 znakow!': 'Password can include only 100 characters!',
  'Potwierdzenie hasla': 'Password confirmation',
  'Potwierdz swoje haslo!': 'Confirm your password!',
  'Pytanie kontrolne':'Security question',
  'Wybierz pytanie kontrolne!':'Choose security question!',
  'Odpowiedz':'Answer',
  'Podaj odpowiedz na pytanie kontrolne!': 'Enter answer for security question!',
  'Odpowiedz musi zawierac co najmniej 6 znakow!': 'Answer has to include at least 6 characters!',
  'Odpowiedz na pytanie kontrolne moze zawierac maksymalnie 100 znakow!':'Security question answer can include only 100 characters!',

  //reset-password
  'Pomyslnie zmieniono haslo.': 'Password change successfully.',
  'Podano bledne dane.':'You have entered incorrect data.',
  'Zmien haslo':'Change password',

  'Austria':'Austria',
  'Belgia':'Belgium',
  'Bulgaria':'Bulgaria',
  'Chorwacja':'Croatia',
  'Cypr':'Cyprus',
  'Czechy':'Czech Republic',
  'Dania':'Denmark',
  'Estonia':'Estonia',
  'Finlandia':'Finland',
  'Francja':'France',
  'Grecja':'Greece',
  'Hiszpania':'Spain',
  'Holandia':'Netherlands',
  'Irlandia':'Ireland',
  'Litwa':'Lithuania',
  'Luksemburg':'Luxemburg',
  'Lotwa':'Lithuania',
  'Malta':'Malta',
  'Niemcy':'Germany',
  'Polska':'Poland',
  'Portugalia':'Portugal',
  'Rumunia':'Romania',
  'Slowacja':'Slovakia',
  'Slowenia':'Slovenia',
  'Szwecja':'Sweden',
  'Wegry':'Hungary',
  'Wielka Brytania':'United Kingdom',
  'Wlochy':'Italy',


  'pytanie1':'What do you see outside the window?',
  'pytanie2':'What are you afraid of the most?',
  'pytanie3':'What do you do best?',
  'pytanie4':'What do you dislike the most?',

  'Gracz: ':'Player: ',
  'Wygrywa gracz: ':'The winner is player: ',
  'Zaloguj sie!':'Log in first!',
  'Jezyk': 'Language',
  'Zamknij':'Close',
  'cookies1':'This website use cookies according to the ',
  'cookiesLink':'Cookies Policy.',
  'cookies2':'By continuing you agree for using them.',


  'O mnie':'About me',
  'Kontakt':'Contact',
  'Doswiadczenie':'Experience',
  'Aby uzyskac dostep do tej strony zaloguj sie.':'You have to log in to access this site.',
  'Zaloguj sie':'Log in',
  'Rejestracja':'Register',
  'O mnie p1':'I am IT student at Warsaw University of Life Sciences with specialisation Information Systems Engineering.',
  'O mnie p2':'I am interested in Astronomy and Astrophysics. In my free time i read books and watch movies.',
  'Adres email':'E-mail address',
  'Numer telefonu':'Phone number',
  'Kliknij tutaj':'Click here',
  'Pracodawca':'Employer',
  'Data':'Date',
  'Zadania':'Tasks',
  'sierpien 2016':'august 2016',
  'Tworzenie aplikacji gieldowej w technologi Java Swing.':'Developing stock market app using Java Swing.'
};
